spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jpa_education
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false